#!/usr/bin/env bash
# Install portable toolchains for the F2 CVA6 bare-metal llama.cpp build.
# No sudo. System gcc-riscv64-unknown-elf is not enough (no newlib / libstdc++).
set -euo pipefail

LLAMA_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ -d /projects/prj1/sle-wajahat/tools ]] || [[ "$(dirname "$LLAMA_ROOT")" == /projects/prj1/sle-wajahat ]]; then
  DEFAULT_TOOLS=/projects/prj1/sle-wajahat/tools
else
  DEFAULT_TOOLS="$(cd "$LLAMA_ROOT/.." && pwd)/tools"
fi
TOOLS_DIR="${TOOLS_DIR:-$DEFAULT_TOOLS}"
mkdir -p "$TOOLS_DIR"

XPACK_VER="15.2.0-1"
XPACK_DIR="xpack-riscv-none-elf-gcc-${XPACK_VER}"
XPACK_TAR="${XPACK_DIR}-linux-x64.tar.gz"
XPACK_URL="https://github.com/xpack-dev-tools/riscv-none-elf-gcc-xpack/releases/download/v${XPACK_VER}/${XPACK_TAR}"
XPACK_SHA256="aaaa8060c914851a3e5ee1ba82cc3d6f80972f90638a05c6e823a37557a33758"

CMAKE_VER="3.30.5"
CMAKE_DIR="cmake-${CMAKE_VER}-linux-x86_64"
CMAKE_TAR="${CMAKE_DIR}.tar.gz"
CMAKE_URL="https://github.com/Kitware/CMake/releases/download/v${CMAKE_VER}/${CMAKE_TAR}"
CMAKE_SHA256="f747d9b23e1a252a8beafb4ed2bc2ddf78cff7f04a8e4de19f4ff88e9b51dc9d"

need_host() {
  local missing=()
  local cmd
  for cmd in curl tar sha256sum; do
    command -v "$cmd" >/dev/null 2>&1 || missing+=("$cmd")
  done
  if ((${#missing[@]})); then
    echo "error: missing host tools: ${missing[*]}" >&2
    echo "  Debian/Ubuntu: sudo apt-get install -y curl tar coreutils" >&2
    exit 1
  fi
}

download_and_extract() {
  local url="$1" tarname="$2" sha="$3" marker_dir="$4"
  if [[ -d "$TOOLS_DIR/$marker_dir" ]]; then
    echo "skip: $marker_dir already present in $TOOLS_DIR"
    return 0
  fi
  echo "download: $url"
  curl -L --fail --retry 3 -o "$TOOLS_DIR/$tarname" "$url"
  echo "${sha}  $TOOLS_DIR/$tarname" | sha256sum -c -
  tar -C "$TOOLS_DIR" -xf "$TOOLS_DIR/$tarname"
  rm -f "$TOOLS_DIR/$tarname"
}

write_env() {
  local envf="$TOOLS_DIR/cva6-env.sh"
  cat >"$envf" <<EOF
# Generated by llama.cpp/setup.sh — source this before building tests/llama.
export XPACK_ROOT="$TOOLS_DIR/$XPACK_DIR"
export CMAKE="$TOOLS_DIR/$CMAKE_DIR/bin/cmake"
export PATH="$TOOLS_DIR/$XPACK_DIR/bin:$TOOLS_DIR/$CMAKE_DIR/bin:\$PATH"
EOF
  echo "wrote $envf"
}

main() {
  if [[ "$(uname -s)" != Linux ]] || [[ "$(uname -m)" != x86_64 ]]; then
    echo "error: this script installs linux-x64 archives (host=$(uname -s)/$(uname -m))" >&2
    exit 1
  fi

  need_host
  echo "TOOLS_DIR=$TOOLS_DIR"
  download_and_extract "$XPACK_URL" "$XPACK_TAR" "$XPACK_SHA256" "$XPACK_DIR"
  download_and_extract "$CMAKE_URL" "$CMAKE_TAR" "$CMAKE_SHA256" "$CMAKE_DIR"

  local gcc_bin="$TOOLS_DIR/$XPACK_DIR/bin/riscv-none-elf-g++"
  local cmake_bin="$TOOLS_DIR/$CMAKE_DIR/bin/cmake"
  [[ -x "$gcc_bin" ]] || { echo "error: missing $gcc_bin" >&2; exit 1; }
  [[ -x "$cmake_bin" ]] || { echo "error: missing $cmake_bin" >&2; exit 1; }
  echo "riscv-none-elf-g++: $("$gcc_bin" --version | head -n1)"
  echo "cmake: $("$cmake_bin" --version | head -n1)"

  if command -v python3 >/dev/null 2>&1 && python3 -m venv --help >/dev/null 2>&1; then
    local venv="$TOOLS_DIR/cva6-gguf-venv"
    if [[ ! -x "$venv/bin/python" ]]; then
      echo "python venv for dummy GGUF (numpy) ..."
      python3 -m venv "$venv"
      "$venv/bin/pip" install -q --upgrade pip
      "$venv/bin/pip" install -q numpy
    else
      echo "skip: $venv already present"
    fi
  else
    echo "note: python3/venv not found; skip GGUF venv (needed only for gen_tiny_gguf.py)"
  fi

  write_env
  echo
  echo "Tool dependencies installed."
  echo "  xPack RISC-V GCC ${XPACK_VER}  (newlib + libstdc++; triple riscv-none-elf)"
  echo "  CMake ${CMAKE_VER}"
  echo
  echo "Next:"
  echo "  source $TOOLS_DIR/cva6-env.sh"
  echo "  # then follow README.md → AWS F2 CVA6 step-by-step"
}

main "$@"
